### ISSUE TITLE
Execution Engine Spec Draft

### ISSUE THREAD

**Issue by isheff** [anoma/specs#123]
Complete an [english-language spec of the execution engine](https://specs.anoma.net/main/components/typhon/execution.html), at least from the Typhon perspective. 

## Sub-Tasks
- [ ] [figure out exactly what Taiga needs](https://hackmd.io/KCTqJMmeSU-H-uI3qoTT5A)
- [ ] [Fix broken LaTeX](https://specs.anoma.net/main/components/typhon/execution.html)
- [ ] Integrate Taiga's needs into Executor spec
- [ ] Establish ability to use / share proofs of some kind as an optimization instead of full replication
- [ ] establish / separate roles of Validator and Full Node
- [ ] add diagrams

## Will Want Eventually
- optimization for aligning Narwhal and Execution engine workers so we need less communication
- re-sharding protocol for re-organizing who stores what within a validator
- decentralized protocols for deciding who constructs execution proofs (if we're not doing full replication)
