### ISSUE TITLE
Taiga spec tracking

### ISSUE THREAD

**Issue by vveiln** [anoma/specs#150]
Created this issue for tracking the Taiga spec progress and discussing the current tasks and issues

Tasks in question:
- [ ] create comprehensive Taiga glossary
- [ ] discuss correspondence to new Anoma terminology and rename the terms
- [ ] split the Taiga spec up
- [ ] Taiga interfaces

**Comment by vveiln** [comment]
Some thoughts I have:

1) **Terminology match**: It might make sense to keep the Taiga terminology different from the Anoma terminology, and just have a clear understanding of how they match. A lot of the Taiga terminology comes with helpful context, Anoma terminology is designed to be general and is naturally less precise and switching might be not beneficial. Don't know if it is a good idea to keep it (will be much clearer after the terminologies matched), but I think it makes sense to consider it

2) **Splitting the spec**: I think it might make sense to separate the Taiga core spec and the part describing the interaction with other components, but splitting the core spec feels not beneficial

3) **Taiga interfaces** are not fully defined yet, and I'm not sure if it makes sense to have them in the spec eventually. On the one hand it feels more suitable for the Taiga crate documentation, but on the other hand describing how Anoma components can interact with Taiga sounds important for the spec. Maybe it can be split into the detailed developer documentation and the spec bit that briefly describes what Taiga gives to components (seems to overlap with the "Taiga functions" section)
